# Generated by Django 6.0.7 on 2026-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelgroup',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_groups/'),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hotelgroup',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotelgroup',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
