# Generated by Django 6.0.7 on 2026-07-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelgroup_options_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hotelgroup',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='database_engine',
            field=models.CharField(default='django.db.backends.postgresql', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='database_host',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='database_port',
            field=models.CharField(default='5432', max_length=10),
        ),
    ]
