# Generated by Django 6.0.7 on 2026-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('assigned_staff_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('dirty', 'Dirty'), ('in_cleaning', 'In Cleaning'), ('clean', 'Clean / Ready'), ('inspected', 'Inspected')], default='dirty', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'housekeeping_tasks',
            },
        ),
    ]
